[workspace]
authors = ["Maulik Madhavi <maulikmadhavi@gmail.com>"]
channels = ["conda-forge"]
name = "qbe-std"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.2,<26"
librosa = ">=0.11.0,<0.12"

[pypi-dependencies]
einops = ">=0.8.1, <0.9"
numpy = ">=2.2.6, <3"
matplotlib = ">=3.10.5, <4"
